# POST https://localhost:8000/api/cards HTTP/1.1
# content-type: application/json

# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"
# }

POST http://localhost:8000/api/cards HTTP/1.1
content-type: application/json

{
    "name": "ayy",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

GET http://localhost:8000/api/cards HTTP/1.1


GET http://google.com HTTP/1.1
